### ISSUE TITLE
"Could you help compile a Windows version with HTTP/3 support?"朋友可以帮忙编译一个windows带http3支持的版本吗

### ISSUE THREAD

**Issue by reyoreyo** [robvanoostenrijk/nginx-http3#1]
"Could you help compile a Windows version with HTTP/3 support?"朋友可以帮忙编译一个windows带http3支持的版本吗

**Comment by robvanoostenrijk** [comment]
I looked into doing this using GitHub actions, but the compilation process on Windows is too different to make this easily work and maintain it.

However, you are welcome to fork and give it a try yourself.
